export const OBTENER_PRODUCTOS_EXITO = 'OBTENER_PRODUCTOS_EXITO';

export const SELECCIONAR_PRODUCTOS = 'SELECCIONAR_PRODUCTOS';

export const ORDENAR_ARTICULO = 'ORDENAR_ARTICULO';

export const MOSTRAR_RESUMEN = 'MOSTRAR_RESUMEN';

export const ELIMINAR_PRODUCTO = 'ELIMINAR_PRODUCTO';

export const PEDIDO_ORDENADO = 'PEDIDO_ORDENADO'